name: summarize-telegram-bot

services:
  summarize-telegram-bot:
    container_name: summarize-telegram-bot
    build: https://github.com/simonmysun/telegram-summarize-bot.git
    init: true
    volumes:
      - /path/to/.env:/app/.env:ro
      - /path/to/prompts/:/app/prompts:ro
    restart: unless-stopped
